version: '3.1'

services:
  at_listing_validator:
    build: ./services/scrapers/auto_trader/listing/validator

    volumes:
      - ./services/libs:/libs

    env_file:
      - .prod.env
    
    network_mode : host