version: '3.1'

services:
  mc_csv_parser:
    build: ./services/scrapers/market_check/csv_parser

    volumes:
      - /home/market_check/ftp/upload:/new_files
      - ./services/libs:/libs

    env_file:
      - .prod.env
    
    network_mode : host

  mc_csv_parser_mysql:
    build: ./services/scrapers/market_check/csv_parser_mysql

    volumes:
      - ./services/libs:/libs

    env_file:
      - .prod.env

    restart: always
    
    network_mode : host

  api:
    build: ./services/api

    volumes:
      - ./services/libs:/libs
      - ./tmp:/tmp

    env_file:
      - .prod.env
    
    network_mode : host

  
  dashboard:
    build: ./services/dashboard

    restart: always
    depends_on:
      - api
      
    ports:
        - "3000:3000"

    env_file: .env

  transform:
    build: ./services/transform

    volumes:
      - ./services/libs:/libs

    env_file:
      - .prod.env
    
    network_mode : host
    
    restart: always
  
  pre_validation:
    build: ./services/pre_validation

    volumes:
      - ./services/libs:/libs

    env_file:
      - .prod.env

    network_mode : host
    
    restart: always
  
  # post_validation:
  #   build: ./services/post_validation

  #   volumes:
  #     - ./services/libs:/libs

  #   env_file:
  #     - .prod.env
    
  #   network_mode : host

  #   restart: always
  
  make_model_prediction:
    build: ./services/ml/prediction/make_model

    volumes:
      - ./services/libs:/libs

    env_file:
      - .prod.env
    network_mode : host

    restart: always
  
  # car_image_prediction:
  #   build: ./services/ml/prediction/car_image

  #   volumes:
  #     - ./services/libs:/libs
  #     - ./media:/media
  #     - ./services/ml/prediction/car_image/model:/usr/src/app/model

  #   env_file:
  #     - .prod.env
    
  #   # deploy:
  #   #     mode: replicated
  #   #     replicas: 3
  #   #     resources:
  #   #       limits:
  #   #         cpus: '4'

  #   network_mode : host

  #   restart: always

  # registration_prediction:
  #   build: ./services/ml/prediction/registration

  #   volumes:
  #     - ./services/libs:/libs
  #     - ./media:/media
  #     - ./services/ml/prediction/registration/model:/usr/src/app/model

  #   env_file:
  #     - .prod.env

  #   network_mode : host
    
  #   restart: always
  
  post_calculation:
    build: ./services/post_calculation

    volumes:
      - ./services/libs:/libs

    env_file:
      - .prod.env
    network_mode : host

    restart: always

    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: '2'
  
  fl_listing_upsert:
    build: ./services/production/listing

    volumes:
      - ./services/libs:/libs

    env_file:
      - .prod.env

    network_mode : host

    restart: always

    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: '2'

  fl_listing_photos_upsert:
    build: ./services/production/photos

    volumes:
      - ./services/libs:/libs
      - ./media:/media

    env_file:
      - .prod.env

    network_mode : host

    restart: always

  # car_cutter:
  #   build: ./services/car_cutter

  #   volumes:
  #     - ./services/libs:/libs
  #     - ./media:/media

  #   env_file:
  #     - .prod.env

  #   network_mode : host

  #   deploy:
  #       mode: replicated
  #       replicas: 5
  #       resources:
  #         limits:
  #           cpus: '2'

  car_cutter_submit:
    build: ./services/car_cutter/submit

    volumes:
      - ./services/libs:/libs
      - ./media:/media

    env_file:
      - .prod.env

    network_mode : host

    restart: always

    deploy:
      mode: replicated
      replicas: 5
      resources:
        limits:
          cpus: '1'

  car_cutter_status_checker:
    build: ./services/car_cutter/status_checker

    volumes:
      - ./services/libs:/libs
      - ./media:/media
    env_file:
      - .prod.env
    
    deploy:
      mode: replicated
      replicas: 25
      resources:
        limits:
          cpus: '1'

    network_mode : host

    restart: always

  car_cutter_downloader:
    build: ./services/car_cutter/downloader

    volumes:
      - ./services/libs:/libs
      - ./media:/media
      - /var/www/html/files:/files

    env_file:
      - .prod.env

    deploy:
      mode: replicated
      replicas: 5
      resources:
        limits:
          cpus: '1'

    network_mode : host

    restart: always

    deploy:
      mode: replicated
      replicas: 5
      resources:
        limits:
          cpus: '1'
  # spyne_ai:
  #   build: ./services/spyne_ai

  #   volumes:
  #     - ./services/libs:/libs
  #     - ./media:/media

  #   env_file:
  #     - .prod.env

  #   network_mode : host

  #   restart: always
  
  image_downloader:
    build: ./services/image_downloader

    volumes:
      - ./services/libs:/libs
      - ./media:/media
      - /var/www/html/files:/files

    env_file:
      - .prod.env

    network_mode : host

    restart: always

    deploy:
      mode: replicated
      replicas: 5
      resources:
        limits:
          cpus: '2'

  generate_image:
    build: ./services/generate_image

    volumes:
      - ./services/libs:/libs
      - ./media:/media
      - /var/www/html/files:/files

    env_file:
      - .prod.env

    network_mode : host

    restart: always